# NOTE: you must draw a square from the top left to top right to bottom right to bottom left.
#       otherwise, the webapp won't render the points correctly.
# start from north west corner (as best as possible)
points:
  - lon: -121.1107158832017
    lat: 37.353951452025434
  - lon: -121.11058914882697
    lat: 37.353951452025434
  - lon: -121.11059048993147
    lat: 37.353876295651744
  - lon: -121.1107158832017
    lat: 37.35387256448231
# draw this out from top (north) to bottom (south)
dimensions:
  - row: 4
    col: 3
